class_mode: binary
layers:
- W_constraint: null
  W_regularizer: null
  activation: sigmoid
  activity_regularizer: null
  b_constraint: null
  b_regularizer: null
  cache_enabled: true
  init: uniform
  input_dim: 20
  input_shape: !!python/tuple [20]
  name: Dense
  output_dim: 64
- {cache_enabled: true, name: Dropout, p: 0.5}
- {W_constraint: null, W_regularizer: null, activation: sigmoid, activity_regularizer: null,
  b_constraint: null, b_regularizer: null, cache_enabled: true, init: uniform, input_dim: null,
  name: Dense, output_dim: 64}
- {cache_enabled: true, name: Dropout, p: 0.5}
- {W_constraint: null, W_regularizer: null, activation: linear, activity_regularizer: null,
  b_constraint: null, b_regularizer: null, cache_enabled: true, init: glorot_uniform,
  input_dim: null, name: Dense, output_dim: 1}
loss: binary_crossentropy
name: Sequential
optimizer: {beta_1: 0.8999999761581421, beta_2: 0.9990000128746033, epsilon: 1.0e-08,
  lr: 0.0010000000474974513, name: Adam}
